CREATE TABLE IF NOT EXISTS delay_api_config (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    queue_type VARCHAR(20) NOT NULL DEFAULT 'redisson',
    delay_time BIGINT NOT NULL DEFAULT 5,
    content VARCHAR(255) NOT NULL DEFAULT '',
    request_method VARCHAR(10) NOT NULL DEFAULT 'POST',
    request_url VARCHAR(1000) NOT NULL,
    request_headers TEXT NULL,
    request_body MEDIUMTEXT NULL,
    callback_method VARCHAR(10) NOT NULL DEFAULT 'POST',
    callback_url VARCHAR(1000) NULL,
    callback_headers TEXT NULL,
    callback_body MEDIUMTEXT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS delay_task (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    message_id VARCHAR(64) NOT NULL UNIQUE,
    queue_type VARCHAR(20) NOT NULL,
    content VARCHAR(255) NOT NULL,
    delay_time BIGINT NOT NULL,
    create_time BIGINT NOT NULL,
    execute_time BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    instance_id VARCHAR(100) NULL,
    request_method VARCHAR(10) NOT NULL DEFAULT 'POST',
    request_url VARCHAR(1000) NULL,
    request_headers TEXT NULL,
    request_body MEDIUMTEXT NULL,
    request_status INT NULL,
    request_response MEDIUMTEXT NULL,
    request_error MEDIUMTEXT NULL,
    callback_method VARCHAR(10) NOT NULL DEFAULT 'POST',
    callback_url VARCHAR(1000) NULL,
    callback_headers TEXT NULL,
    callback_body MEDIUMTEXT NULL,
    callback_status INT NULL,
    callback_response MEDIUMTEXT NULL,
    callback_error MEDIUMTEXT NULL,
    executed_at BIGINT NULL,
    updated_at BIGINT NOT NULL,
    INDEX idx_delay_task_status (status),
    INDEX idx_delay_task_create_time (create_time)
);
